### ISSUE TITLE
Legend by marker color instead of Icon

### ISSUE THREAD

**Issue by akshaykaul** [sghaskell/Clustered-Single-Value-Map-Visualization#13]
hi, is it possible to have an option to select whether the marker legend be based on icon or marker colour.
In my use case I want to use the same Icon but the markers are coloured differently based on certain field value. Willing to have an option to select / unselect markers based on colour using legend rather than icons.

Thank you
Regards
Akshay,

![cluster map1](https://user-images.githubusercontent.com/33046841/31922634-9d9b2492-b8d2-11e7-99d3-5b111c4901cd.PNG)
![cluster map2](https://user-images.githubusercontent.com/33046841/31922662-d1cf0e9a-b8d2-11e7-955f-a53ed10061f6.PNG)

**Comment by sghaskell** [comment]
Thanks for the suggestion @akshaykaul . I'll have a look into this.

**Comment by sghaskell** [comment]
Here's a modification using a field in the search named **layerGroup**.  Would this be helpful?

<img width="1559" alt="screen shot 2017-10-30 at 3 02 30 pm" src="https://user-images.githubusercontent.com/8450537/32198020-ae96cea8-bd83-11e7-899f-5948d2be9672.png">

**Comment by akshaykaul** [comment]
Hi Scott,

Thank you for looking into this one. Yes that should work, can control the legend using the value for layerGroup field.

Regards,
Akshay

**Comment by akshaykaul** [comment]
![capture_layer](https://user-images.githubusercontent.com/33046841/32200697-d6872232-be37-11e7-81f5-d0813a5bcef6.PNG)


Hi Scott, so I am guessing will need to update the viz app in order for the new field to take effect..

**Comment by sghaskell** [comment]
@akshaykaul Yes, I'll need to push the changes and publish a new version of the app. The default behavior will stay the same unless you use the **layerGroup** field.

**Comment by sghaskell** [comment]
@akshaykaul 

I've released [version 1.5.9 on Splunkbase](https://splunkbase.splunk.com/app/3124/). This includes the new feature for specifying **layerGroup** in SPL. Try it out and let me know if it's working well for your needs.

**Comment by akshaykaul** [comment]
Hi Scott,
thank you again. The feature is working perfectly  and serves the purpose in our use case.

Regards
Akshay,
![layergroup](https://user-images.githubusercontent.com/33046841/32357079-44b4efec-c09e-11e7-946f-1e6e9d21d4ef.PNG)

**Comment by sghaskell** [comment]
Thanks @akshaykaul . Thanks for the useful feature request and I'm glad it's working well for you!
