### ISSUE TITLE
Failed to load source in Firefox

### ISSUE THREAD

**Issue by Kaiyaran** [sghaskell/Clustered-Single-Value-Map-Visualization#15]
Hello!

I have some trouble with a cluster Map visualization, which is driving me crazy...

I'm working with two instances of Splunk (both of them using Firefox and Chrome):

Testing-Local: 6.5.4
Prod-Server: 6.6.2
App version: 1.5.10

The thing is, I am not able to visualize the cluster map, just with firefox, in the Prod-Server 6.6.2 version of Splunk, and I don't know why... The error message says "Failed to load source for Clustered Single Value Map Visualization visualization".
I've checked for copatibilities, tags, addons... But nothing. I don't know what I'm missing, and it's really strange that I can't see the map just with firefox, on the 6.6.2 Prod-Server.

Any thoughts about what is happening here? Maybe any deprecated tag? I checked them too, but I'm not using any deprecated tags...

Here are the visualizations:
Testing-Local: 6.5.4
![image](https://user-images.githubusercontent.com/12073390/33368352-c075e8f4-d4f1-11e7-8ecc-900b1bfb75bf.png)

Prod-Server: 6.6.2 
![image](https://user-images.githubusercontent.com/12073390/33368371-d1bd4d1e-d4f1-11e7-96e1-7574b589235a.png)

Thank you very much!!

**Comment by sghaskell** [comment]
Thanks for submitting the issue, @Kaiyaran . I'll Have a look and see if I can't replicate it. Could you tell me the version of Firefox and what OS you're running?

**Comment by Kaiyaran** [comment]
I'm using Firefox  53.0 (32-bit) on Windows 7 Enterprise (64 bit)

**Comment by sghaskell** [comment]
Thanks @Kaiyaran. I was able to replicate the problem and found the issue. Please try version 1.5.11 that is now live on Splunkbase. The culprit was babel-polyfill.

**Comment by Kaiyaran** [comment]
Thanks for the quick fix @sghaskell ! As soon as I can test it again i'll tell you.

Many thanks!!

**Comment by sghaskell** [comment]
@Kaiyaran - Did you get a chance to test this out?

**Comment by Kaiyaran** [comment]
Hello @sghaskell, sorry for the delay on responding you, I was out and couldn't test it until now.
I've already tested it and it works perfectly! 

Thanks for fix!
