### ISSUE TITLE
How Many Points will support this APP

### ISSUE THREAD

**Issue by joelurtubia** [sghaskell/Clustered-Single-Value-Map-Visualization#17]
Scott I need your help please, I've read that this APP will support 1.7 MM UP of markers, but I try to get 5 K of markers and my splunk service is not enougth for show me this information, I don't know if I have a problem on my splunk service or my laptop,  can you share with me a minimum requeirements of  my splunk server that I need, please?

I have this HW configuration on my splunk

[root@ACC-IX-SPLUNK joel.urtubia]# free -h
              total        used        free      shared  buff/cache   available
Mem:            15G        2,5G        8,1G        312M        4,9G         12G
Swap:          2,0G        127M        1,9G
[root@ACC-IX-SPLUNK joel.urtubia]# nproc --all
12

should be enougth? please help me to solved it.
thanks!!

**Comment by sghaskell** [comment]
Hi @joelurtubia . I apologize for the delay but I totally missed this issue during the run-up to the holiday break. The map and points are actually rendered on the client computer through the browser. Make sure your computer has enough memory and you're using a modern, performant browser. Are you using clustering or do you have that disabled? Disabling clustering will lead to degraded performance depending on the number of points you're mapping.

**Comment by joelurtubia** [comment]
Thanks Scott, I used a clustering disabled , I'll enabled it ....then the main problem is with my laptop, I should fix it..
thanks for your reply!!!, have a great day!!!
