### ISSUE TITLE
Unable to parse &amp; to & on mapTileOverride option.

### ISSUE THREAD

**Issue by jeddelosreyes** [sghaskell/Clustered-Single-Value-Map-Visualization#20]
Hi,  Since the _&amp;_ was being escaped by _getEscapedProperty. 
This link will not work as expected: http://mt1.google.com/vt/lyrs=y&amp;x={x}&amp;y={y}&amp;z={z}
because character reference for ampersand is not converted properly. 
Is it possible to retain these code below:

mapTileOverride  = SplunkVisualizationUtils.makeSafeUrl(config[this.getPropertyNamespaceInfo().propertyNamespace + 'mapTileOverride'])

**Comment by sghaskell** [comment]
@jeddelosreyes Thanks for pointing this out. I do make a call to `makeSafeUrl`, but the underlying method uses `escapeHtml` when it returns which causes an issue.

See [here](https://github.com/sghaskell/Clustered-Single-Value-Map-Visualization/blob/master/appserver/static/visualizations/leaflet_maps/src/leaflet_maps.js#L390) and [here](https://github.com/sghaskell/Clustered-Single-Value-Map-Visualization/blob/master/appserver/static/visualizations/leaflet_maps/src/leaflet_maps.js#L157)

I've already tested a fix and I'll push it out for you today. Thanks for reporting!

**Comment by sghaskell** [comment]
@jeddelosreyes this is now fixed in version 1.5.14 on Splunkbase.
