### ISSUE TITLE
Google map address search

### ISSUE THREAD

**Issue by meenalluktuke** [sghaskell/Clustered-Single-Value-Map-Visualization#5]
Hi,

Similar to https://splunkbase.splunk.com/app/368/, is there any plan to search for custom addresses in the map? Very similar to the Google Maps address search - not the navigation, only geocoding (return lat,lon from an address).

**Comment by sghaskell** [comment]
Thanks for the enhancement request. I'll look into the feasibility of making this happen. Most of the Leaflet search plugins revolve around searching markers/GeoJSON features on the map. There is one plugin that integrates with the Google Places search API.

http://leafletjs.com/plugins.html#search--popups

Although there's no address search functionality with fly to, you can currently right click on the map at any point to return the lat/lon of the mouse pointer. Make sure the format menu setting **Map -> Context Menu** is **Enabled** (enabled by default). Right click on the map and select **Show details** and you'll get the coordinates.

<img width="1597" alt="screen shot 2017-04-24 at 9 01 13 am" src="https://cloud.githubusercontent.com/assets/8450537/25346545/b8435616-28cc-11e7-992e-9865ffebde20.png">

<img width="1596" alt="screen shot 2017-04-24 at 9 01 01 am" src="https://cloud.githubusercontent.com/assets/8450537/25346578/cf22d898-28cc-11e7-973e-076e48edee4b.png">

**Comment by sghaskell** [comment]
@meenalluktuke 

I just release version 1.5.6 with Google Places API integration. Just enable the feature in the format menu under **Google Places** and plug your API key in. You can customize the location of the search bar. 

This version of the feature will fly to the desired zoom level but it does not place a marker on the map. It's not a search for markers that are already drawn on the map. This is simply the Google Places search bar to allow a place/address search and fly to that location.

Let me know if there are any other actions you'd like to see from the feature.

[5f14ca6](https://github.com/sghaskell/Clustered-Single-Value-Map-Visualization/commit/52134e0007a5eef534e44df46a666b1df5f14ca6)
