### ISSUE TITLE
Display a custom value from a field instead of an icon

### ISSUE THREAD

**Issue by simcen** [sghaskell/Clustered-Single-Value-Map-Visualization#6]
Instead of an icon, I would like to print a number or string from a field.
Is this already possible somehow?

**Comment by sghaskell** [comment]
Thanks for reaching out. This isn't currently supported but I could possibly add the feature. Just to clarify; you want numbers on the individual markers, correct? Something like this?

http://moravcik.github.io/Leaflet.TextIcon/

<img width="900" alt="screen shot 2017-04-25 at 10 37 03 am" src="https://cloud.githubusercontent.com/assets/8450537/25399109/2ac71d2c-29a3-11e7-93ba-abd9f92ca61e.png">

The one problem with doing this is if your numbers are large enough to exceed the size of the marker (likely more than 3-4 digits) it can lead to readability issues.

Your best bet right now is to leverage the **description** field to house your string/number and use **markerColor** and/or **icon** to style the marker to indicate its importance. This can give you some immediate feedback but you'll need to click on the marker to see the contents of the popup.

 If there aren't a lot of markers that you're plotting you can set the format menu options **Clustering -> Enable Clustering -> No**, **Clustering -> Show All Popups -> Yes** and **Clustering -> Allow Multiple Popups -> Yes**. This will show all the popups by default when the map is loaded to show the contents of the popup without having to click on the icon.

**Comment by simcen** [comment]
Thanks, that's exactly what we would need. I see the point regarding large numbers but we would be fine if the marker supports 3-4 digits.

As you mentioned, right now we've leveraged **description** and the **markerColor**. But for accuracy reasons, the customer likes to see the numbers directly. 

There are like 50 markers, each representing a site of the customer so I disabled clustering anyway. 

Feel free to reach out if you want to get some more insights about our use case.

**Comment by sghaskell** [comment]
@simcen 

Try installing the latest version of the app (1.5.6). There's a new field called **tooltip** and a new **Markers** format menu to customize the behavior of the tooltip. Although it doesn't render into the actual marker, it's a cleaner, more compact way of display a number/label on a marker without having to expand the details. It also works with clustering enabled.

If you don't enable permanent tooltip, you can just hover over the marker to display the text.

<img width="1604" alt="screen shot 2017-07-10 at 12 23 20 pm" src="https://user-images.githubusercontent.com/8450537/28035803-cd6f7a3a-656a-11e7-8e5f-2b71d97ad179.png">
