### ISSUE TITLE
Using tokens as center lat/long values

### ISSUE THREAD

**Issue by pgthompson** [sghaskell/Clustered-Single-Value-Map-Visualization#8]
Hi Scott

We have a use case where we want to use a static zoom value but re-center the map when a new search runs (the search generates new lat/long values which we are putting into tokens and then using the token  as the center values i.e.
<option name="leaflet_maps_app.leaflet_maps.mapCenterLat">$addr_lat$</option>
<option name="leaflet_maps_app.leaflet_maps.mapCenterLon">$addr_long$</option>
<option name="leaflet_maps_app.leaflet_maps.mapCenterZoom">12</option>
This works on inital search but not on any subsequent searches. Have tried unsetting the token values but no luck.
Any help appreciated...Paul

**Comment by simobe** [comment]
I have the same problem with Splunk Enterprise 6.6.1 and version 1.5.2 of the app.

**Comment by sghaskell** [comment]
Thanks for reporting this, Paul. Are you attempting to persist the static zoom value as one of the format menu options in the visualization? By design, the Custom Visualization API does not allow you to dynamically set format menu options and persist them.

If you don't need to persist the menu option, I can look into exposing new fields for updating the center lat/lon values dynamically via search and override the defaults.

**Comment by pgthompson** [comment]
Hi Scott

We are attempting to use dynamically updated tokens as the map center lat/long values so when the search updated and then the token values the map would re-centre to the new location (the zoom value is static, so not changed)
i.e.

<option name="leaflet_maps_app.leaflet_maps.mapCenterLat">$lat$</option>
<option name="leaflet_maps_app.leaflet_maps.mapCenterLon">$long$</option>
<option name="leaflet_maps_app.leaflet_maps.mapCenterZoom">10</option>

Regards Paul

**Comment by sghaskell** [comment]
Paul,

I'm testing out a new feature that will auto-fit the map to all the markers with the maximum zoom level possible. This will dynamically set the position of the map without having to provide any parameters or tokenization. If **Center Lat**, **Center Lon** and **Map Zoom** are set, the map would initially render on those points but once all the data is done loading it would auto-fit based on what was drawn on the map. I also added a context menu option called **Fit Map To Boundaries** that makes navigating back out to all coordinates simple with a right click on the map. I'll also add a format menu option to toggle the feature on/off.

It should make life easier for everyone and achieve a similar result. Does that address your use case?

**Comment by pgthompson** [comment]
Hi Scott

It certainly sounds promising. So from what you’ve said, each time the data is updated (with new lat/long values) the map will redraw and centre/zoom based on the new data?
Looking forward to trying it out!

Cheers Paul

**Comment by sghaskell** [comment]
That's correct, Paul! I'll get a new release out tomorrow with the feature.

**Comment by joelurtubia** [comment]
Paul... I've readed all post, and also thanks for your replies.. I  have the same problem, when do you plain to solved it? I have the version 6.5.1
please let me know, thanks and have a great day.

**Comment by sghaskell** [comment]
The **Auto Fit & Zoom** feature is now in version 1.5.4 and is available on [Splunkbase](https://splunkbase.splunk.com/app/3124/). Please give it a try and let me know how it works for you.
 
[Release 7e5673b](https://github.com/sghaskell/Clustered-Single-Value-Map-Visualization/commit/7e5673bb8b7c605cf59c15f36c080c03407f2c3f)

**Comment by joelurtubia** [comment]
Very Sorry Paul, but I've load the lates version of this addon but still not working, attached my dashboard
I've created first a input query into my top of dashboard n and I use this values as tokens to center my map... I was made something wrong, could you help me please?

thanks, I'll apreciated a lot

[Dashboard.txt](https://github.com/sghaskell/Clustered-Single-Value-Map-Visualization/files/1129799/Dashboard.txt)

**Comment by pgthompson** [comment]
Hi Scott

Looks awesome!
I am getting some inconsistent rendering with the map so I setup a test page to try and demonstrate what’s happening.
For example.
I have a test page with a Region dropdown which when changed, runs a new search and then re- centres to the new region.
The top map is result of selecting region A.
I then changed region to region B and the map re-rendered fine and re-centred.
I then selected region A again and the map re-rendered but this time it didn’t zoom in. (bottom map).
It’s not always when I go back to the same region either, it could be a different one altogether.
I’m testing in Chrome.

Thanks, Paul

[cid:image002.jpg@01D2F73B.DFD539F0]

[cid:image004.jpg@01D2F73B.DFD539F0]


[cid:image009.jpg@01D2F73B.DFD539F0]

**Comment by sghaskell** [comment]
Thanks, Paul. I've replicated what you're seeing and I believe I have a fix. I'll get a new version out shortly.

**Comment by joelurtubia** [comment]
sorry, my post is for Scott

Very Sorry Scott, but I've load the lates version of this addon but still not working, attached my dashboard
I've created first a input query into my top of dashboard n and I use this values as tokens to center my map... I was made something wrong, could you help me please?

thanks, I'll apreciated a lot

**Comment by sghaskell** [comment]
Paul,

Please try version 1.5.6. I've added a format menu option called **Auto Fit & Zoom Delay (ms)** that will delay the firing. The default is 500 ms and in my testing it has performed consistently. You can bump it up if you're seeing different behavior.

Scott

**Comment by sghaskell** [comment]
@joelurtubia ,

I have implemented a new feature called **Auto Fit & Zoom** which will dynamically fit the map at the highest zoom level possible for the given markers on the map. This should give you the best default view of your map. You can enable it in the format menu at **Map (Continued) -> Auto Fit & Zoom -> Enabled**

I haven't done much testing with dynamically setting the options using tokens, but my guess is it may not work as desired. You can access [search event handlers](http://docs.splunk.com/Documentation/Splunk/6.3.3/Viz/EventHandlerReference#Search_event_handlers) to set tokens, but there may be a race condition between when the token gets set and my code reads it. My guess is that the preview handler may be the only one that will work since the finalized and done handlers likely fire too late and my code probably won't pickup those tokens. Your best bet is to use the new Auto Fit & Zoom feature.

Scott

**Comment by joelurtubia** [comment]
Thanks Scott !!!, let me try it and I'll let you know, for while I've created a dashboard that opened a new link map in other browser and also pass those tokens, and its work....

**Comment by sghaskell** [comment]
@joelurtubia 

Clever idea! I just posted version 1.5.7 to Splunkbase. I had some reports that 1.5.6 had inconsistent results processing events so I reverted the logic back. Hopefully that works for you.

**Comment by joelurtubia** [comment]
Thanks for your reply Scott, I'll try it asap...

**Comment by joelurtubia** [comment]
Now was working as I expect, great Job Scott.

**Comment by pgthompson** [comment]
Thanks Scott

It’s working well…awesome job!
Paul
