### ISSUE TITLE
Legend visible instead of toggle

### ISSUE THREAD

**Issue by meenalluktuke** [sghaskell/Clustered-Single-Value-Map-Visualization#9]
Hi Scott,

I was trying to make the legend "always visible" rather than toggle. However the code changed in my local copy does not reflect on Splunk installed on same server (Wanted to try it locally).

Can you help me?

I just modified the var iconHtml to remove class legend-toggle-icon in the file leaflet_maps.js

Thanks,
Meenal

**Comment by sghaskell** [comment]
Hi @meenalluktuke ,

If you want to re-build the visualization for testing you'll need to install NPM. Once installed, navigate to **$SPLUNK_HOME/etc/apps/leaflet_mapps_app/appserver/static/visualizations/leaflet_maps**

Run the following command to install all the dependencies:

`$ npm install`

Now run the following to build the visualization.js file from leaflet_maps.js

`$ npm run build`

If you don't have a local copy of Node.js you can leverage the one packaged with Splunk but you'll need to update **package.json** to point to it. Just modify this section.

```
"scripts": {
    "build": "/path/to/splunk_home/bin/splunk cmd node ./node_modules/webpack/bin/webpack.js",
    "devbuild": "node ./node_modules/webpack/bin/webpack.js --progress",
    "watch": "node ./node_modules/webpack/bin/webpack.js -d --watch --progress"
  },
```

It's also helpful to create $SPLUNK_HOME/etc/system/local/web.conf and put your instance into dev mode so source isn't minified or cached

```
[settings]
minify_js = False
minify_css = False
js_no_cache = True
cacheEntriesLimit = 0
cacheBytesLimit = 0
enableWebDebug = True
```
